groups:
  - name: kmc.rules
    rules:
    - alert: KMCDown
      expr: up{job="kyma-metrics-collector", namespace="kyma-system"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        description: KMC has disappeared from Prometheus target discovery for the last 5 minutes.
  - name: kmc.rules.edp
    rules:
    - alert: EDPRequestFailures
      expr: sum by (status) (increase(kmc_edp_request_total{status!~"2.."}[5m])) > 20
      for: 10m
      labels:
        severity: critical
      annotations:
        description: KMC has failed to call EDP with status "2xx successful" in the last 5 minutes.
    - alert: EDPRequestDuration
      expr: sum by (job) (rate(kmc_edp_request_duration_seconds_sum[30m])/rate(kmc_edp_request_duration_seconds_count[30m])) > 3
      for: 10m
      labels:
        severity: warning
      annotations:
        description: Average request duration to EDP during the last 30 minutes took longer than 3 seconds.
  - name: kmc.rules.keb
    rules:
    - alert: KEBRequestFailures
      expr: sum by (status) (increase(kmc_keb_request_total{status!~"2.."}[5m])) > 20
      for: 10m
      labels:
        severity: critical
      annotations:
        description: KMC has failed to call KEB with status "2xx successful" in the last 5 minutes.
    - alert: KEBRequestDuration
      expr: sum by (job) (rate(kmc_keb_request_duration_seconds_sum[30m])/rate(kmc_keb_request_duration_seconds_count[30m])) > 5
      for: 10m
      labels:
        severity: warning
      annotations:
        description: Average request duration to KEB during the last 30 minutes took longer than 5 seconds.
    - alert: ClustersRateChanged
      expr: (deriv(kmc_keb_number_clusters_scraped[5m])) < -0.033
      for: 5m
      labels:
        severity: critical
      annotations:
        description: Within 5 minutes the numbers of clusters scraped decreased by at least 10 clusters.
  - name: kmc.rules.skr
    rules:
    - alert: SKRErrors
      expr: sum without (reason) (kmc_skr_calls_total{status="success"}) / ignoring (status) sum without (reason, status) (kmc_skr_calls_total) < 0.4
      for: 10m
      labels:
        severity: critical
      annotations:
        description: KMC has reported an increase in errors in the last 10 minutes for SKR.
  - name: kmc.rules.gardener
    rules:
    - alert: GardenerErrors
      expr: sum by (reason) (increase(kmc_gardener_calls_total{status="failure"}[5m])) > 30
      for: 10m
      labels:
        severity: critical
      annotations:
        description: KMC has reported an increase in errors in the last 10 minutes for Gardener.