{{- if .Values.global.kyma_metrics_collector.enabled -}}
{{- if .Values.prometheus.rules.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{ include "kyma-metrics-collector.prometheusrule.labels" . | indent 4 }}
  name: {{ include "kyma-metrics-collector.fullname" . }}
  namespace: {{ .Values.prometheus.namespace }}
spec:
  groups:
    - name: kmc.rules
      rules:
      - alert: KMCDown
        expr: up{job={{ .Values.prometheus.job | quote }}, namespace={{ .Values.prometheus.namespace | quote }}} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: KMC has disappeared from Prometheus target discovery for the last 5 minutes.
    - name: kmc.rules.edp
      rules:
      - alert: EDPRequestFailures
        expr: sum by (status) (increase(kmc_edp_request_total{status!~"2.."}[5m])) > 20
        for: 10m
        labels:
          severity: critical
        annotations:
          description: KMC has failed to call EDP with status "2xx successful" in the last 5 minutes.
      - alert: EDPErrors
        expr: sum by (subaccount) (increase(kmc_edp_error_count[5m])) > 30
        for: 10m
        labels:
          severity: critical
        annotations:
          description: KMC has reported an increase in errors in the last 10 minutes for EDP.
      - alert: EDPRequestDuration
        expr: sum by (job) (rate(kmc_edp_request_duration_seconds_sum[30m])/rate(kmc_edp_request_duration_seconds_count[30m])) > 3
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Average request duration to EDP during the last 30 minutes took longer than 3 seconds.
    - name: kmc.rules.keb
      rules:
      - alert: KEBRequestFailures
        expr: sum by (status) (increase(kmc_keb_request_total{status!~"2.."}[5m])) > 20
        for: 10m
        labels:
         severity: critical
        annotations:
          description: KMC has failed to call KEB with status "2xx successful" in the last 5 minutes.
      - alert: KEBErrors
        expr: sum by (job) (increase(kmc_keb_error_count[5m])) > 30
        for: 10m
        labels:
          severity: critical
        annotations:
          description: KMC has reported an increase in errors in the last 10 minutes for KEB.
      - alert: KEBRequestDuration
        expr: sum by (job) (rate(kmc_keb_request_duration_seconds_sum[30m])/rate(kmc_keb_request_duration_seconds_count[30m])) > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Average request duration to KEB during the last 30 minutes took longer than 5 seconds.
      - alert: ClustersRateChanged
        expr: (deriv(kmc_keb_number_clusters_scraped[5m])) < -0.033
        for: 10m
        labels:
          severity: critical
        annotations:
          description: Within 5 minutes the numbers of clusters scraped decreased by at least 10 clusters.
    - name: kmc.rules.skr
      rules:
      - alert: SKRErrors
        expr: sum by (subaccount) (increase(kmc_skr_error_count[5m])) > 30
        for: 10m
        labels:
          severity: critical
        annotations:
          description: KMC has reported an increase in errors in the last 10 minutes for SKR.
    - name: kmc.rules.gardener
      rules:
      - alert: GardenerErrors
        expr: sum by (subaccount) (increase(kmc_gardener_error_count[5m])) > 30
        for: 10m
        labels:
          severity: critical
        annotations:
          description: KMC has reported an increase in errors in the last 10 minutes for Gardener.
    - name: kmc.rules.cache
      rules:
      - alert: CacheErrors
        expr: sum by (subaccount) (increase(kmc_cache_error_count[5m])) > 30
        for: 10m
        labels:
          severity: critical
        annotations:
          description: KMC has reported an increase in errors in the last 10 minutes for the Cache.
    - name: kmc.rules.publiccloud
      rules:
      - alert: ProviderErrors
        expr: sum by (job) (increase(kmc_public_cloud_error_count[5m])) > 30
        for: 10m
        labels:
          severity: warning
        annotations:
          description: KMC has reported an increase in errors in the last 10 minutes for loading the public cloud specs.
{{- end -}}
{{- end -}}