apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{ include "kyma-metrics-collector.labels" . | indent 4 }}
  name: {{ include "kyma-metrics-collector.fullname" . }}
  namespace: kcp-system
spec:
  endpoints:
   - port: http
  namespaceSelector:
    matchNames:
    - kcp-system
  selector:
    matchLabels:
{{ include "kyma-metrics-collector.labels" . | indent 8 }}
